name: 'Amplify push'
on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set branch name
        id: setenvname
        run: |
          # Get the branch name from the current commit (which is dev after merging)
          echo "##[set-output name=setbranchname;]$(echo ${GITHUB_REF##*/})"

      - name: Deploy to existing Amplify branch
        uses: yinlinchen/amplify-preview-actions@master
        with:
          branch_name: ${{ steps.setenvname.outputs.setbranchname }}
          amplify_command: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AmplifyAppId: ${{ secrets.AMPLIFY_ID_STAGING }}
          AWS_REGION: ${{ secrets.AWS_BUCKET_REGION }}
