name: Deploy frontend to AWS Amplify
on:
  push:
    branches:
      - staging
env:
  APP_ID: d3u69tpukpw2yo
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{secrets.AWS_BUCKET_REGION}}
      AWS_DEFAULT_OUTPUT: json
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: ./scripts/amplify-deploy.sh d3u69tpukpw2yo staging
