name: Deploy to AWS Amplify
on:
  push:
    branches:
      - staging
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_BUCKET_REGION }}
      - uses: actions/checkout@v2
      - name: Deploy
        env:
          APP_ID: ${{secrets.AMPLIFY_ID_STAGING}}
        run: ./scripts/amplify-deploy.sh $APP_ID staging
