name: Deploy frontend to AWS Amplify
on:
  push:
    branches:
      - staging
env:
  APP_ID: ${{ secrets.AMPLIFY_ID_STAGING }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{secrets.AWS_BUCKET_REGION}}
      AWS_DEFAULT_OUTPUT: json
      BRANCH: ${{ steps.extract_branch.outputs.branch }}
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: ./scripts/amplify-deploy.sh $APP_ID $BRANCH
